### ISSUE TITLE
ForEachAsync continues after cancellation token is cancelled

### ISSUE THREAD

**Issue by da1rren** [dotnet/reactive#1940] opened 2023-05-19 10:13 UTC
### Which library version?
System.Reactive.Async 6.0.0-alpha.3
System.Reactive.Linq 5.0.0"

##### What are the platform(s), environment(s) and related component version(s)?
N/A

### What is the use case or problem?
Cancelling ForEachAsync should stop the enumeration. 

### What is the expected outcome?
Enumeration stopped after token cancelled

### What is the actual outcome?
Enumeration continues forever

### Do you have a code snippet or project that reproduces the problem?
```csharp
using System.Reactive.Linq;

var observable = AsyncObservable.Interval(TimeSpan.FromSeconds(1));

var cancellationTokenSource = new CancellationTokenSource();
cancellationTokenSource.CancelAfter(TimeSpan.FromSeconds(5));

await observable.ForEachAsync(seconds =>
{
    Console.WriteLine($"Seconds: {seconds}, Is Cancelled: {cancellationTokenSource.Token.IsCancellationRequested}");
}, cancellationTokenSource.Token);
```

<img width="343" alt="image" src="https://github.com/dotnet/reactive/assets/2702382/1de61731-cb6f-4126-a6b7-a79343b8a663">

I might be just completely misunderstanding but the behaviour seems odd.

**Comment by idg10** [comment] 2023-06-29 15:36
Having reproduced this and traced through the behaviour, I think we've found the problem. It's here:

https://github.com/dotnet/reactive/blob/95d9ea9d2786f6ec49a051c5cff47dc42591e54f/AsyncRx.NET/System.Reactive.Async/Linq/Operators/ForEachAsync.cs#L127-L129

The call to `await tcs.Task.ConfigureAwait(false);` occurs after a closing `}` that corresponds to this `using` statement further up the file:

https://github.com/dotnet/reactive/blob/95d9ea9d2786f6ec49a051c5cff47dc42591e54f/AsyncRx.NET/System.Reactive.Async/Linq/Operators/ForEachAsync.cs#L61-L73

Once we reach that closing `}`, we `Dispose` the `CancellationTokenRegistration` returned by `CancellationToken.Register`, which means we're telling the `CancellationToken` that we are no longer interested in being notified when cancellation occurs.

But that's too early. We should do this only _after_ the `ForEachAsync` has finished. So the call to `await tcs.Task.ConfigureAwait(false);` should move inside that code block to ensure that we don't unregister for cancellation until after the for each logic has reached an end.

**Comment by idg10** [comment] 2023-06-29 15:43
So, although this isn't going to be terribly complex to fix, the larger problem here is that because Async.Rx was always an experimental feature, it doesn't have any tests.

https://github.com/dotnet/reactive/issues/1900

Normally when fixing a bug I like to ensure that tests exist that would detect the problem so we can avoid regressions, and possibly detect other problems of a similar nature.

However, I'm not sure how soon we'll be able to address the lack of tests. As you can see from that other issue, we are hoping to work out some way of sharing test logic across normal and async Rx, so that we don't have to maintain two parallel, near-identical sets of tests. But that's a fairly large undertaking, and not something we expect to complete imminently. So we could just fix this without a test as a stopgap.

Is this problem causing you problems right now, or was it just a curiosity that you noticed? If this is blocking you, I'll fix it without waiting until we have a proper answer for how to test AsyncRx.NET.

**Comment by da1rren** [comment] 2023-06-29 16:14
It was for something experimental, so please don't feel you have to fix it for myself.  Feel free to close if you'd rather track the issue in another way.

**Closed** 2023-07-27 21:24 UTC
Labels: [area] AsyncRx
