### ISSUE TITLE
Namespace collision with DbSet of Ef core

### ISSUE THREAD

**Issue by aleGuardiola** [dotnet/reactive#1058] opened 2019-10-18 19:31 UTC
The EntityFramework Core  DbSet<Entity> implements IEnumerable and IAsyncEnumerable as well what cause a collision because the extensions for IAsyncEnumerable are in the same namespace: "System.Linq", one solution can be changing the namespace for the IAsyncEnumerable extensions maybe something like "System.Linq.Async"

**Comment by onovotny** [comment] 2019-10-18 19:43
Dup of #1057

The issue is that DbSet implements both of those interfaces and thus both sets of extension methods apply.

Closing as by design. You can use AsQueryable() to distinguish.

**Closed by onovotny** 2019-10-18 19:43 UTC

**Comment by aleGuardiola** [comment] 2019-10-18 19:49
That will be quick fix but also I consider it is a limitation, because I cannot use the benefits of the IAsyncEnumerable of Ef core or probably other class or interface that support  both implementations.

**Comment by onovotny** [comment] 2019-10-18 19:50
I would take it up with the EF team -- it's how they designed their type.

**Comment by SimonCropp** [comment] 2019-11-06 05:27
fyi i reopened https://github.com/dotnet/reactive/issues/1057
