### ISSUE TITLE
when SubscribeOn a collection ,we cannot receive any notification

### ISSUE THREAD

**Issue by Luoyingliang** [dotnet/reactive#1498] opened 2021-03-09 01:02 UTC
I want to observe a collection changed and process the notification in another thread,but when i call SubscribeOn method,it doesn't work, when i remove the SubscribeOn method it work so well.

Environment:
SDK : .Net 5.0 SDK
LIB: ReactiveUI 13.0.1
ReactiveUI.WPF 13.0.1
System.Reactive 5.0.0
OS: Windows 10
#### Bug

``` C#
public class Model
    {
        public string Text { get; set; }
    }

    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        private ObservableCollection<Model> Collection;
        public MainWindow()
        {
            InitializeComponent();

            //
            // it test can subscribeOn method work on thread pool scheduler
            Collection = new ObservableCollection<Model>();
            Observable.FromEventPattern<NotifyCollectionChangedEventArgs>(Collection, "CollectionChanged")
                      .ObserveOn(RxApp.MainThreadScheduler)
                      .SubscribeOn(RxApp.TaskpoolScheduler)
                      .Select(x => x!)
                      .Subscribe(x =>RxApp.TaskpoolScheduler.Schedule(()=> Debug.WriteLine($"collection work on thread:{Thread.CurrentThread.ManagedThreadId}")));
            Collection.Add(new Model());
        }
    }
```
> Please describe the feature.

**Comment by Luoyingliang** [comment] 2021-03-09 01:04
When add SubscribeOn Method , it print noting,
When Remove SubscribeOn Method , it print :
> collection work on thread:4

**Comment by cabauman** [comment] 2021-03-09 01:35
Because of SubscribeOn, `Collection.Add(new Model());` gets executed _before_ the subscription is made. To demonstrate, if you add `Thread.Sleep(1000);` before `Collection.Add(new Model());` you'll get the log you're looking for.

**Comment by bartdesmet** [comment] 2021-05-21 17:27
@cabauman's analysis is correct; the use of `SubscribeOn` here causes the event handler attachment to be delayed (and, in fact, due to the way `FromEventPattern` works with regards to capturing the current `SynchronizationContext`, the event handler attachment will still end up being queued to the UI thread), so the handler isn't attached yet by the time the `Add` method is called.

What's the reason to try to use `SubscribeOn` to attach an event handler (which is a cheap operation) on the task pool? Is you goal instead to offload the event processing (using `ObserveOn`) to a different thread?

Either way, the code above behaves as designed in Rx. I'll close the issue as there's no bug to be fixed, but feel free to reply with any question that can help to clarify what you're trying to achieve.

**Closed by bartdesmet** 2021-05-21 17:27 UTC
Labels: [area] Rx
