### ISSUE TITLE
Zip commutativity (or lack-of)

### ISSUE THREAD

**Issue by gluck** [dotnet/reactive#142] opened 2015-10-15 14:53 UTC
Zip implementation can be surprising in scenarios where one of the stream completes much before the other. Although it should know (if no unbuffered item remains) that the end result stream should terminate, it'll only do so when a new event occurs on the other stream.

Concretely it means:

```
        var a = Observable.Range(0, 1);
        var b = Observable.Range(0, 2).Concat(Observable.Never<int>());

        a.Zip(b, (i, j) => i + j).Wait(); // finishes
        b.Zip(a, (i, j) => i + j).Wait(); // never finishes
        new[] { a, b }.Zip(l => l.Sum()).Wait(); // finishes
        new[] { b, a }.Zip(l => l.Sum()).Wait(); // never finishes
```

One would expect the behavior of a.Zip(b) and b.Zip(a) to be closer to each other.

Note that although rx-marbles exhibits the same behavior, rx-java does not, and completes the zip'ed stream as soon as possible, as expected.

**Comment by akarnokd** [comment] 2016-07-20 13:18
Yes, we buffer each source and track its completed state. Whenever one source fires, we see if we can collect a row of values for the function, if one of the source's buffer is empty and is also marked as completed, we don't bother further; cancel all sources and emit `onCompleted` right away (plus we are also lock-free on the emission path).

**Comment by akarnokd** [comment] 2019-11-13 21:46
I think the `Zip` behavior in Rx.NET is by design. @bartdesmet can you confirm?

**Comment by akarnokd** [comment] 2019-12-04 16:18
Closing as works as intended.

**Closed by akarnokd** 2019-12-04 16:18 UTC
Labels: [area] Rx, question
