### ISSUE TITLE
Remove dependency on System.ValueTuple NuGet package when targeting .Net framework 4.7

### ISSUE THREAD

**Issue by Andrej-Peplinski** [dotnet/reactive#840] opened 2018-11-05 13:28 UTC
This is to avoid having to add unnecessary dependencies in consuming projects.

**Comment by bartdesmet** [comment] 2019-04-10 21:20
@onovotny, is this something that still needs attention?

This may bring a little pickle when we add overloads for e.g. `Zip` that use `ValueTuple<...>` to be symmetric with newer extension methods added to `IEnumerable<T>`. In particular:

```csharp
public static IObservable<(TFirst First, TSecond Second)> Zip<TFirst, TSecond>(this IObservable<TFirst> first, IObservable<TSecond> second);
```

**Comment by onovotny** [comment] 2019-04-10 21:27
It's probably worth adding another build target for the first version of .NET that has ValueTuple in it.

**Comment by joshjje** [comment] 2019-05-20 12:53
I third this.

**Comment by glopesdev** [comment] 2020-05-30 14:08
Are there any plans to move forward on this? Is there a good reason to keep targeting net46 when `System.Reactive` requires `System.ValueTuple` anyway? In that case might as well just target net472.

**Comment by glopesdev** [comment] 2020-05-30 14:23
I guess another way to look at it is to consider the `netstandard2.0` target as the compatibility layer for net47 applications (since `netstandard2.0` does include `System.ValueTuple`). In that case, maybe a possible "resolution" for the issue is to simply remove the `net46` target?

**Comment by bartdesmet** [comment] 2020-09-29 18:49
@clairernovotny, let's address this before we hit 5.0 RTM. I'm happy to drop 4.6 and either add 4.7.2, or just converge on `.netstandard2.0` for downlevel support.

**Comment by clairernovotny** [comment] 2020-09-30 18:31
I think we can set net472 as the new min esp since it's a major version bump. Having a net472 tfm is good for two reasons:

- Reduces binding redirect issues with netstandard libraries
- Has our WinForms and WPF support

**Comment by bartdesmet** [comment] 2020-10-01 00:11
This has been addressed now and will be in Rx 5.0.

**Closed by bartdesmet** 2020-10-01 00:11 UTC
Labels: [area] Rx
