### ISSUE TITLE
Request: Add RuntimeInformation 4.3.0 to nuspec dependency for PCL target

### ISSUE THREAD

**Issue by amay077** [dotnet/reactive#448] opened 2017-11-18 12:27 UTC
I got the error listed below when add ``System.Reactive`` nuget package to PCL project.

> Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

## HOW TO REPRO

1. Create PCL project (PCL 4.5 - Profile 111)
2. Add "System.Reactive v3.1.1" nuget package
3. Getting above error

## WORKAROUND

1. Create PCL project (PCL 4.5 - Profile 111)
2. **Add "[System.Runtime.InteropServices.RuntimeInformation 4.3.0](https://www.nuget.org/packages/System.Runtime.InteropServices.RuntimeInformation/4.3.0)" nuget package manually**
3. Add "System.Reactive v3.1.1" nuget package
4. Works fine!

This workaround is brought from @yamachu - [Link(Japanese)](http://teitoku-window.hatenablog.com/entry/2017/11/18/185501).
## REQUEST

I hope you add ``System.Runtime.InteropServices.RuntimeInformation 4.3.0`` to System.Reactive's nuspec dependency for PCL target.
It will solves this issue. 

## RELATED LINKS

* [Microsoft.NETCore.Platforms doesn't install on packages.config based projects · Issue #8952 · dotnet/corefx](https://github.com/dotnet/corefx/issues/8952)

**Comment by yamachu** [comment] 2017-11-19 02:38
"System.Reactive.Linq v3.1.1" depends on "System.Runtime.InteropServices.WindowsRuntime (>= 4.0.1)".
"System.Runtime.InteropServices.WindowsRuntime" version should be more than 4.3.0, because it depends on "System.Runtime (>= 4.1.0)".
Additionaly "System.Runtime (>= 4.1.0)" depends on "Microsoft.NETCore.Platforms (>= 1.0.1)" that is the root cause.

So it seems that it is better to update this dependency.

**Comment by danielcweber** [comment] 2018-05-23 09:02
@amay077 Is this still an issue with the latest preview of Rx.net 4.0 ?

**Comment by onovotny** [comment] 2018-05-26 16:50
Closing since Rx4 does not support legacy PCL's anymore. It is netstandard2.0+

**Closed by onovotny** 2018-05-26 16:50 UTC
Labels: on-hold-until-community-reforms-join-us-in-slack
