### ISSUE TITLE
cannot use dynamic variables with RX IObservable objects

### ISSUE THREAD

**Issue by muusbolla** [dotnet/reactive#817] opened 2018-09-30 20:44 UTC
```
dynamic d = Observable.Return<int>(12345);
d.Subscribe(anything); //exception - "object" does not contain a definition for "Subscribe"
```
The objects returned by static Observable methods (for example `Observable.Return<int>(12345);` and probably also extension methods like IObservable.Select) appear to implement the IObservable interface explicitly. When they are assigned to a variable of 'dynamic' type, this has the side effect that the Subscribe method cannot be accessed. This is apparently due to a C# language feature by design (https://stackoverflow.com/questions/11625947/use-explicit-interface-implementations-with-a-dynamic-object). I hope that is the issue and not this one related to internal classes -> (http://www.jameswiseman.com/blog/2013/05/14/runtimebinderexception-does-not-contain-a-definition-for/)

*edit: After digging into the RX.net source code a bit, it looks like it is more likely the second problem related to internals not being visible to the dynamic object, and not an explicit interface implementation problem. I am not sure. Either way, I have the same problem consuming the library.

The usual "fix" is to use a reference to the specific interface type. This defeats the purpose of using dynamic, and doesn't work for my project. Due to the complexities of my type mapper, I am essentially calling `IObservable<T1>.Subscribe(IObserver<T2>)` where both the observer and the observable are being pulled from separate dictionaries that contain multiple types. I can guarantee that T1 == T2, but I can't instantiate an interface reference variable of either type at runtime. So I need to use dynamic variables for both objects.

I have a workaround that uses a wrapper class that just implements IObservable by wrapping what RX returns. This allows dynamic to find the Subscribe method call. I have to create one of these wrappers for each IObservable<T> that will be used with dynamic variables. But this seems very kludgy and I would prefer if RX was dynamic-friendly up front :)

```
using System;
using System.Reactive.Linq;

namespace ReactiveDynamicTest
{
    public class SinkInt : IObserver<int>
    {
        public void OnNext(int value)
        {
            Console.WriteLine(value);
        }
        public void OnError(Exception error) { }
        public void OnCompleted() { }
    }
    class Program
    {
        static void Main(string[] args)
        {
            SinkInt sink = new SinkInt();

            dynamic dSource = Observable.Return<int>(12345);

            //This line throws exception "object" does not contain a definition for "Subscribe"
            dSource.Subscribe(sink);

            //These lines work, but I can't do this in my implementation
            IObservable<int> oSource = dSource as IObservable<int>;
            oSource.Subscribe(sink);

            //This is my workaround
            dynamic wrappedSource = new ObsWrapper<int>(Observable.Return<int>(12345));
            wrappedSource.Subscribe(sink);

            Console.ReadLine();
        }
    }

    class ObsWrapper<T> : IObservable<T>
    {
        IObservable<T> obj;
        public ObsWrapper(IObservable<T> input)
        {
            obj = input;
        }
        public IDisposable Subscribe(IObserver<T> observer)
        {
            return obj.Subscribe(observer);
        }
    }
}
```

**Comment by danielcweber** [comment] 2018-10-01 09:16
Can you provide a simplest working example of what doesn't work today?

**Comment by muusbolla** [comment] 2018-10-02 03:14
```
public class SinkInt : IObserver<int>
    {
        public void OnNext(int value)
        {
            Console.WriteLine(value);
        }
        public void OnError(Exception error) { }
        public void OnCompleted() { }
    }

class Program
    {
        static void Main(string[] args)
        {
            SinkInt sink = new SinkInt();
            
            dynamic dSource = Observable.Return<int>(12345);

            //This line throws exception "'object' does not contain a definition for 'Subscribe'"
            dSource.Subscribe(sink);
   }
}
```

**Comment by danielcweber** [comment] 2018-10-02 09:18
Funnily enough, your example works for me! I guess it's then a matter of the framework/language version/version of Microsoft.CSharp/whatever. Please post a complete project structure (possibly separate repo).

**Comment by danielcweber** [comment] 2018-10-11 12:01
Closing: Not reproducible on up-to-date versions of compiler/framework/library. Exact setup of OP unclear, no answer. Please reopen with a complete project structure as repro if the problem persists.

**Closed by danielcweber** 2018-10-11 12:01 UTC

**Comment by muusbolla** [comment] 2018-10-20 20:40
I also tried updating my Microsoft.CSharp reference to 4.5 and still getting the same error

**Comment by danielcweber** [comment] 2018-10-20 22:51
Alright, I am unable to get your sample project to work either. It worked for me before because I ran it as a unit test in the System.Reactive project itselft. The difference is that the internals of the System.Reactive assembly are made visible to that test project. So unfortunately, since internals of Rx are invisible to your project, your example won't work without the workaround.

**Comment by muusbolla** [comment] 2018-10-22 19:13
Should I be able to make it work if I recompile Rx.net with all internal specifiers removed? Or include the Rx.net source in my project?

**Comment by danielcweber** [comment] 2018-10-23 07:20
>Should I be able to make it work if I recompile Rx.net with all internal specifiers removed?
 
I would definitely not recommend this, you'll be having a hard time keeping your code up-to-date. You could link Rx-sources into your solution, you'd still have to add that InternalsVisibleTo... attribute, but I'd also not recommend that. If possible, I'd reduce the use of dynamic to a few places and go with the wrapper solution. Add a nice extension method that does the wrapping, it'll look like one of the usual operators. See if that works for you.
