### ISSUE TITLE
`removeHandler` delegate passed to `Observable.FromEventPattern` method not invoked immediately when subscription object is disposed

### ISSUE THREAD

**Issue by DanStevens** [dotnet/reactive#1526] opened 2021-04-23 12:21 UTC
Forgive me if this is not a bug and by design. If it is the latter, please treat this issue as a question: I'd appreciate help understand why Rx works this way.

I have noticed that when calling `Dispose` on a subscription object, the `removeHandler` delegate/Action is not invoked immediately but short while later, outside the flow of the method where `Dispose` is called. I noticed this behavior as I was setting the object being observed to null immediately after called `Dispose`, such that by the time `removeHandler` was invoked the observed object was null. The following code should illustrate:

```csharp
using System;
using System.Reactive;
using System.Reactive.Linq;
using System.Windows;

namespace WpfAppRxTesting
{
    public partial class MainWindow : Window
    {
        private MyThingWithEvent thing;
        private MyObservingClass observer;

        public MainWindow()
        {
            InitializeComponent();
        }

        protected override void OnInitialized(EventArgs e)
        {
            base.OnInitialized(e);

            this.thing = new MyThingWithEvent();
            this.observer = new MyObservingClass(thing);
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            this.thing.InvokeTheEvent();
        }

        protected override void OnClosed(EventArgs e)
        {
            base.OnClosed(e);

            this.observer?.Dispose();
        }
    }

    public class MyThingWithEvent
    {
        public event EventHandler TheEvent;

        public void InvokeTheEvent() => TheEvent?.Invoke(this, EventArgs.Empty);
    }

    public sealed class MyObservingClass : IDisposable
    {
        private MyThingWithEvent subject;
        private IDisposable subscription;

        public MyObservingClass(MyThingWithEvent subject)
        {
            this.subject = subject;
            this.subscription = Observable.FromEventPattern(
                    addHandler: eh => this.subject.TheEvent += eh,
                    removeHandler: eh => this.subject.TheEvent -= eh) // Throws NullReferenceException when invoked
                .Subscribe(this.HandleTheEvent);
        }

        private void HandleTheEvent(EventPattern<object> obj)
        {
            MessageBox.Show("TheEvent handled");
        }

        public void Dispose()
        {
            this.subscription?.Dispose();
            this.subject.InvokeTheEvent(); // `HandleTheEvent` method isn't invoked even though `removeHandler` hasn't ran yet??
            this.subject = null; // Removing this line stops the NullReferenceException above
        }
    }
}
```

From my relatively naive position I'm not certain how much of a problem this behavior may cause in practice, but the following potential concerns come to mind:
  1. What if `subject` is a large object that needs to be set to null in the `Dispose` method?
  2. What if `TheEvent` event is triggered between calling `Dispose` and the `removeHandler` delegate being invoked. I tested this and `HandleTheEvent` method is not ran even though the `removeHandler` delegate hasn't been invoked (according to the visual debugger`). This seems like magic to me.

Full source code for the above available on request. I'm using version 5.0.0 of Rx .NET. If this behavior is all by design, I appreciate any explanation or insight you give. Otherwise, I hope my observations are useful to the project.

**Comment by bartdesmet** [comment] 2021-05-21 16:54
This behavior is by design due to synchronization issues that arose in the Rx 2.0 days when we started to support the UWP platform (back then code-named "Jupiter") which is more strict about where event attach/detach operations should happen. The full nitty-gritty details are documented in the comment over at https://github.com/dotnet/reactive/blob/9f2a8090cea4bf931d4ac3ad071f4df147f4df50/Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEvent.cs#L10. We decided to take the breaking change then in order for existing code to continue to work as-is when ported to other UI platforms that exhibit this strictness around event event handlers. Unfortunately, that does away with synchronous dispose guarantees.

In a nutshell, `FromEvent*` captures the current `SynchronizationContext`, if there's any, and wraps it in a scheduler, over here https://github.com/dotnet/reactive/blob/9f2a8090cea4bf931d4ac3ad071f4df147f4df50/Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Events.cs#L353. Note that the default constructor is used, which exhibits "always post" behavior, see https://github.com/dotnet/reactive/blob/9f2a8090cea4bf931d4ac3ad071f4df147f4df50/Rx.NET/Source/src/System.Reactive/Concurrency/SynchronizationContextScheduler.cs#L26. Disposal of the last subscription to the observable returned from `FromEvent*` then triggers disposal through that scheduler, see https://github.com/dotnet/reactive/blob/9f2a8090cea4bf931d4ac3ad071f4df147f4df50/Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEvent.cs#L292.

So my guess is that the code fragment shown above is running in some context where `SynchronizationContext.Current` is not null, thus causing the post behavior for the dispose.

If the `TheEvent` event is relaxed with regards to the thread from which the `-=` unregistration happens, you can easily use the `Observable.Create<T>` factory to achieve a similar "bridge" to the event, which does not have implicit synchronization behavior:

```csharp
Observable.Create<EventPattern<object>>(observer =>
{
    EventHandler<object> h = (sender, args) => observer.OnNext(new EventPattern<object>(sender, args));
    this.subject.TheEvent += h;
    return Disposable.Create(() => this.subject.TheEvent -= h);
});
```

**Comment by bartdesmet** [comment] 2021-08-24 21:33
Closing this issue given there's no known bug and a suggestion was provided to work around this behavior. Yet another alternative would be to change the original code as follows:

```csharp
        public MyObservingClass(MyThingWithEvent subject)
        {
            this.subject = subject;
            this.subscription = Observable.FromEventPattern(
                    addHandler: eh => subject.TheEvent += eh,
                    removeHandler: eh => subject.TheEvent -= eh) // Throws NullReferenceException when invoked
                .Subscribe(this.HandleTheEvent);
        }
```

I.e. use `subject` rather than `this.subject` in the add/remove handler callbacks. As long as the `this.subscription` gets properly disposed, all handlers on the subject will eventually get removed as well, and there shouldn't be any leak that holds the `MyThingWithEvent` instance alive indefinitely.

**Closed by bartdesmet** 2021-08-24 21:33 UTC
Labels: [area] Rx
