### ISSUE TITLE
Observable.Merge with scheduler over Group (of GroupBy operator) loosing data

### ISSUE THREAD

**Issue by bnayae** [dotnet/reactive#177] opened 2016-05-04 05:50 UTC
this is how you can reproduce the issue

the following code swallow the item

``` csharp
var scd = new TestScheduler();

var source = Observable.Return(1, scd)
    .Concat(Observable.Never<int>());
var xs = from item in source
            group item by item % 3 == 0 into g
                from x in Observable.Merge(
                    g.FirstOrDefaultAsync(),
                    g.LastOrDefaultAsync(), scd)
                select x;

xs.Subscribe(Console.WriteLine);
scd.AdvanceBy(3);
```

if you remove the scheduler from the merge it will produce output

``` csharp
Observable.Merge(
                    g.FirstOrDefaultAsync(),
                    g.LastOrDefaultAsync() /*, scd */)
```

**Comment by akarnokd** [comment] 2016-07-20 12:28
The problem is that `GroupBy` emits the group `Observable`s (that are essentially `PublishSubject`s) that have to be subscribed to immediately to avoid data loss. Since `SubscribeOn` delays the subscription by moving it to another thread with an async scheduler there is no one to observe the the group events for some time. The `Window` operator has the same issue.

This problem can be solved by using an `UnicastSubject` instead of a `PublishSubject` inside these operators. This kind of subject accepts only one `Observer` and buffers events until one arrives. If one arrives, it replays the buffered events and once it caught up, keeps relaying the live events then on. No data loss but of course may lead to buffer bloat - which is generally true for many queue-using operator in Rx.NET anyway.

**Comment by Noggog** [comment] 2018-08-15 22:06
I'm running into this problem as well.  I saw somewhere (maybe the javascript implementation?) had an option to specify what type of subject would be created in the internal dictionaries.  

The change would be modifying [this line](https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/System.Reactive/Linq/Observable/GroupBy.cs#L115) to instead call a Func<ISubject> instead of making a stock one.   This would obviously need to trickle up optional api to allow the user to provide that func.

Would this be a good solution perhaps for some users?  Users could then overload it and put in a ReplaySubject(1) if that was good enough for them.

Being able to immediately catch onto the derivative grouped observables would still be a problem, but maybe having that option would help some people

**Closed** 2019-11-13 21:23 UTC
Labels: [area] Rx, question
