### ISSUE TITLE
Documentation is obsolete and not up-to-date.

### ISSUE THREAD

**Issue by SittenSpynne** [dotnet/reactive#1277] opened 2020-08-26 15:02 UTC
#### Question

I'm experimenting with `TestScheduler`. If I search for it on http://docs.microsoft.com, I get "no results".

https://docs.microsoft.com/en-us/search/?scope=.NET&terms=TestScheduler

If I search with another search engine, I can get a page that warns me it is no longer actively maintained:

https://docs.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh229166(v=vs.103)

That page is a bit obsolete. For example, if I browse to the bottom and look at "Extension Methods", when I click on `Schedule()`, that takes me to a 404. If I click on the `Extensions` class, it says it's part of a ReactiveTests namespace that doesn't seem to exist. I don't even see it in your source repo.

This is frustrating, and also means a lot of example code such as at http://introtorx.com doesn't work. I don't have time to dig through changesets and figure out if this existed at one time and was removed, if I'm barking up the wrong tree, etc.

**Comment by cabauman** [comment] 2020-08-27 13:22
I have a task in progress to improve/update the copy that was cloned to [https://www.reactiveui.net/reactive-extensions](https://www.reactiveui.net/reactive-extensions/): reactiveui/website#441.

**Comment by bartdesmet** [comment] 2020-09-25 04:54
Closing as a duplicate of https://github.com/dotnet/reactive/issues/836. Action items can be discussed over there, including possible community contributions.

**Closed by bartdesmet** 2020-09-25 04:54 UTC
Labels: [area] Rx
