### ISSUE TITLE
Unexpected behavior from IScheduler.Schedule for iterator overload

### ISSUE THREAD

**Issue by shovonnn** [dotnet/reactive#223] opened 2016-07-11 21:39 UTC
> ```
>       return Observable.Create<byte[]>(o =>
>       {
>           source.Seek(offset, SeekOrigin.Begin);
>           var buffer = new byte[bufferSize];
>           var onGoingReadTask = new SerialDisposable();
>           var scheduledTask = new SerialDisposable();
>           Action<Action> iterator = (self) =>
>               onGoingReadTask.Disposable = >Observable.FromAsync((CancellationToken token) => source.ReadAsync(buffer, 0, bufferSize, token))
>                         .Subscribe(count =>
>                         {
>                             Console.WriteLine("from inside:" + count);
>                             if (count > 0)
>                             {
>                                 o.OnNext(buffer.Take(count).ToArray());
>                               self();
>                             }
>                             else
>                                 o.OnCompleted();
>                         }, o.OnError);
>           scheduledTask.Disposable = Scheduler.CurrentThread.Schedule(iterator);
>           return new CompositeDisposable(scheduledTask, onGoingReadTask);
>       });
> ```

consider the observable sequence. if a subscriber dispose the subscription, it also disposes the disposable returned by scheduler. but the iterators still keeps running. which is not expected. if add the following code my problem gets resolved. but it is really unexpected behavior and i had spend few hours on a bug because of this!

> ```
>                                 if (scheduledTask.IsDisposed == false)
>                                     self();
> ```

**Comment by shiftkey** [comment] 2016-07-12 18:00
Are you able to isolate this in a unit test so I can reproduce this on my end?

**Comment by akarnokd** [comment] 2018-05-25 09:50
Can't reproduce with preview 4 and the following setup:

```cs
var source = Observable.Create<int>(observer =>
{
    var count = 0;
    var onGoingReadTask = new SerialDisposable();
    var scheduledTask = new SerialDisposable();
    Action<Action> iterator = (self) =>
        onGoingReadTask.Disposable = Observable.FromAsync(
            token => Task.Delay(100, token).ContinueWith(t => ++count, token)
        ).Subscribe(value => {
            Console.WriteLine("from inside:" + count);

            self();
        })
        ;

    scheduledTask.Disposable = Scheduler.CurrentThread.Schedule(iterator);

    return new CompositeDisposable(onGoingReadTask, scheduledTask);
});

Console.WriteLine(">> Starting");

var d = source.Subscribe();

Thread.Sleep(3000);


d.Dispose();

Console.WriteLine(">> Disposed, waiting a bit more");
Console.WriteLine(">> should not print many more 'from inside:'");

Thread.Sleep(3000);
```

Note though that `Task.Delay.ContinueWith` is not an `ReadAsync` but I'd guess `ReadAsync` is tested well enough so that it responds to the cancellation token properly.

**Comment by danielcweber** [comment] 2018-05-25 10:17
@shovonnn Can you retry/confirm ?

**Comment by akarnokd** [comment] 2019-11-13 20:56
Closing as resolved with 4.x for some time now.

**Closed by akarnokd** 2019-11-13 20:56 UTC
Labels: [area] Rx, bug
