### ISSUE TITLE
Documentation is seriously lacking

### ISSUE THREAD

**Issue by Hermholtz** [dotnet/reactive#1187] opened 2020-04-08 10:48 UTC
While looking for documentation I got lost. What I was searching for was the .NET API reference documentation with all namespaces, classes, methods, properties, extension methods etc. All in one place, describing current version of Rx. Just like most of .NET docs are done on docs.microsoft.com, for example https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic. I'm aware of old Rx docs on Microsoft site, keep reading.

In main README.md it says:
> Additional documentation, video, tutorials and HOL are available on MSDN, on Introduction to Rx...

* MSDN documentation is dead. It says the last update was in 2011. It's a pity because this is the docs that describe stuff the best (if complete).
* introtorx.com mentions version 1.0.10621.0 and says that 2.0 is largely the same. No word about 3.0. It advertises training from 2015 (5 years ago). So it's dead.
* reactivex.io is strange. It doesn't even handle https (which is not related to content, but shows how dead it is - now when it is so easy to obtain Let's Encrypt cert for free.) 
* reactivex.io - there's no easy link to API reference documentation for .NET. Only the pointer to this github repo which points back to reactivex.io. Maybe it's buried somewhere deep in the site's structure, I wasn't able to find it so far.

Maybe it's worth stop adding features for a while, take a step back and update docs instead.

**Comment by mrakgr** [comment] 2020-04-10 13:59
I am wondering what `AsyncRx.NET` and `Ix.NET` in the Rx repo even are.

**Comment by GeeWee** [comment] 2020-04-28 18:58
Definitely a big lack. It seems like many methods are documented in code comments, but I also can't find any comprehensive online documentation or API reference anywhere.

**Comment by elipriaulx** [comment] 2020-07-26 23:24
Is there any proposed location or structure for documentation going forward. How could a nobody go about contributing to this?

**Comment by bartdesmet** [comment] 2020-09-25 04:54
Closing as a duplicate of https://github.com/dotnet/reactive/issues/836. Action items can be discussed over there, including possible community contributions.

**Closed by bartdesmet** 2020-09-25 04:54 UTC
Labels: [area] Rx
