### ISSUE TITLE
Where is the nuget package for System.Reactive.Async

### ISSUE THREAD

**Issue by metasong** [dotnet/reactive#1264] opened 2020-08-02 16:08 UTC
Where is the nuget package for System.Reactive.Async

**Comment by Zuendelmeister** [comment] 2020-09-01 08:55
I would also like to know. Thanks =)

**Comment by bartdesmet** [comment] 2020-09-24 18:36
Closing as duplicate of https://github.com/dotnet/reactive/issues/1248. Continuing tracking over there.

**Closed by bartdesmet** 2020-09-24 18:36 UTC
Labels: [area] Rx
