### ISSUE TITLE
After Nuget System.Interactive.Async 3.2.0 to 4.0.0-preview.1.build.745

### ISSUE THREAD

**Issue by drkorobov** [dotnet/reactive#876] opened 2019-03-18 21:58 UTC
BC42105	Function '<anonymous method>' doesn't return a value on all code paths. A null reference exception could occur at run time when the result is used.	

BC42105	Function '<anonymous method>' doesn't return a value on all code paths. A null reference exception could occur at run time when the result is used.

```vb 
Dim speech = SpeechClient.Create()
                Dim streamingCall = speech.StreamingRecognize()
                Await streamingCall.WriteAsync(New StreamingRecognizeRequest() With {
                        .StreamingConfig = New StreamingRecognitionConfig() With {
                            .Config = New RecognitionConfig() With {
                                .Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
                                .SampleRateHertz = 16000,
                                .LanguageCode = "ru"
                            },
                            .InterimResults = True
                        }
                    })
                Dim printResponses As Task = Task.Run(Async Function()
                                                          While Await streamingCall.ResponseStream.MoveNext(Nothing)
                                                              For Each result In streamingCall.ResponseStream.Current.Results
                                                                  For Each alternative In result.Alternatives
```

streamingCall.ResponseStream - not defined anymore

**Comment by drkorobov** [comment] 2019-03-18 22:02
BC31091	Import of type IAsyncEnumerator(Of ) from assembly or module System.Interactive.Async.dll failed.

**Comment by onovotny** [comment] 2019-03-18 22:11
Ix Async 4 is a breaking change and requires consumers to recompile against it. What library are you using?

**Comment by drkorobov** [comment] 2019-03-18 22:17
`?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Google.Api.CommonProtos" version="1.6.0-beta01" targetFramework="net472" />
  <package id="Google.Api.Gax" version="2.7.0-beta01" targetFramework="net472" />
  <package id="Google.Api.Gax.Grpc" version="2.7.0-beta01" targetFramework="net472" />
  <package id="Google.Apis" version="1.38.0" targetFramework="net472" />
  <package id="Google.Apis.Auth" version="1.38.0" targetFramework="net472" />
  <package id="Google.Apis.Core" version="1.38.0" targetFramework="net472" />
  <package id="Google.Cloud.Speech.V1" version="1.1.0" targetFramework="net472" />
  <package id="Google.LongRunning" version="1.1.0" targetFramework="net472" />
  <package id="Google.Protobuf" version="3.7.0" targetFramework="net472" />
  <package id="Grpc.Auth" version="1.19.0" targetFramework="net472" />
  <package id="Grpc.Core" version="1.19.0" targetFramework="net472" />
  <package id="Grpc.Core.Api" version="1.19.0" targetFramework="net472" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" targetFramework="net472" />
  <package id="NAudio" version="1.9.0-preview2" targetFramework="net472" />
  <package id="Newtonsoft.Json" version="12.0.1" targetFramework="net472" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.6.0-preview3.19128.7" targetFramework="net472" />
  <package id="System.Interactive.Async" version="4.0.0-preview.1.build.745" targetFramework="net472" />
  <package id="System.IO" version="4.3.0" targetFramework="net472" />
  <package id="System.Linq.Async" version="4.0.0-preview.1.build.745" targetFramework="net472" />
  <package id="System.Net.Http" version="4.3.4" targetFramework="net472" />
  <package id="System.Runtime" version="4.3.1" targetFramework="net472" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.6.0-preview3.19128.7" targetFramework="net472" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.1" targetFramework="net472" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net472" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net472" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.2" targetFramework="net472" />
  <package id="System.Threading.Tasks.Extensions" version="4.6.0-preview.18571.3" targetFramework="net472" />
  <package id="WindowsAPICodePack-Core" version="1.1.2" targetFramework="net472" />
</packages>`

**Comment by bartdesmet** [comment] 2019-04-10 16:59
The one line that definitely will need to be changed to adapt to the new interfaces is this:

```vb
While Await streamingCall.ResponseStream.MoveNext(Nothing)
```

to

```vb
While Await streamingCall.ResponseStream.MoveNextAsync()
```

**Comment by drkorobov** [comment] 2019-04-10 17:24
https://d.radikal.ru/d10/1904/f9/1e209e38dacf.jpg

to ... not recognize (((

**Comment by hazzik** [comment] 2019-09-30 04:43
>Ix Async 4 is a breaking change and requires consumers to recompile against it. 

@onovotny this is not always the case. I think the library should declare `[TypeForwardedToAttribute]` to show that type has moved. 

My case: I want to support EF Core 2.0 and EF Core 3.0 in the same library.

**Comment by danielcweber** [comment] 2019-09-30 08:35
>My hypothesis, that if the TypeForwardedTo is declared then case 3 would be solved for me.
@hazzik I fear it's not that simple. Ix-Async interfaces from v3 and v4/.netstandard 2.1 are incompatible and can't be just forwarded to. Do you need to reference EF Core 2.0 and 3.0 from the same target framework of your library? Or would you be able to target EF Core 2.0 for the .netstandard2 compilation of your library while targeting EF Core 3.0 for the .netstandard2.1 compilation?

**Comment by hazzik** [comment] 2019-09-30 09:14
> I fear it's not that simple. Ix-Async interfaces from v3 and v4/.netstandard 2.1 are incompatible and can't be just forwarded to.

Yes, I understand that they are not compatible. For me it's not a problem though.

>Do you need to reference EF Core 2.0 and 3.0 from the same target framework of your library? Or would you be able to target EF Core 2.0 for the .netstandard2 compilation of your library while targeting EF Core 3.0 for the .netstandard2.1 compilation?

I want to avoid having different version of dependency depending on target framework. In this case it's better (for me) to just create 2 separate libraries.

**Comment by onovotny** [comment] 2019-11-10 19:01
Closing as this is all by design. The shape of the interface changed as @danielcweber noted. The good news is that the interface is part of the BCL.

**Closed by onovotny** 2019-11-10 19:01 UTC
