### ISSUE TITLE
Observable.Generate - delay between result calculation and forwarding onNext

### ISSUE THREAD

**Issue by richk1** [dotnet/reactive#865] opened 2019-01-26 18:20 UTC
Observable.Generate is not behaving as I would expect it to. I would expect that when the resultSelector() is executed, the result would be sent to the observer using onNext immediately. Instead it appears that the timeSelector() is executed first, and onNext isn't forwarded until after the next scheduled invocation occurs at the new time. I've browsed through the source of Generate.cs a bit (a lot of it is beyond me, but I think I get the gist) and it seems to match the (incorrect?) behavior I'm seeing. 
I'd think that 
```csharp
if (_hasResult) ForwardOnNext(_result);
```
ought to go after the try/catch block that calculates the _result, so that the result is forwarded in the same invocation pass. (in [Generate.cs](https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/System.Reactive/Linq/Observable/Generate.cs#L302) lines 302-305 ought to be moved to 331) Looking back through the history I see some cases where it seemed to have been written that way: [example](https://github.com/dotnet/reactive/blob/34ef5d04458d01102da8f1d4dafd9ace6c4a6ea8/Rx.NET/Source/src/System.Reactive/Linq/Observable/Generate.cs#L316).

As I see it, I don't think there's anyway to use Generate, as it is, to get non-zero time between onNexts and still get the onNext forwarded to the observer immediately. Is this a bug, or intended behavior that just doesn't do what I'd like it to (or am using incorrectly)? I'm new to C#/Reactive, so forgive me if I'm missing something obvious. Thanks

**Comment by bartdesmet** [comment] 2019-04-10 19:24
This seems to be behaving as designed originally. The relevant lines to compare are [current](https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/System.Reactive/Linq/Observable/Generate.cs#L298) and [original](https://github.com/dotnet/reactive/blob/34ef5d04458d01102da8f1d4dafd9ace6c4a6ea8/Rx.NET/Source/src/System.Reactive/Linq/Observable/Generate.cs#L163).

The design is as follows. For every iteration, check if we have to terminate by evaluating the condition; if so, call `OnCompleted` immediately. Evaluate *all* predicates and selectors in the current iteration, because if something throws an exception, we should call `OnError` immediately (and not defer that, which is a core principle in Rx - akin to the "immediate" nature of `throw ex;` - that also drove the design of this operator). This includes figuring out what the result is going to be, thus calling the result selector. Finally, if everything is successful, defer emitting the result on the observable sequence based on the calculated time.

I can see that the alternative behavior of deferring the evaluation of the result may be desirable as well, but that's easily achieved by emitting the original value and using a `Select` operator right after it to perform such evaluations. One of the benefits of Rx is that the composition of operators often enables you to achieve what you want, even if some operators do not have the behavior you may expect.

**Comment by richk1** [comment] 2019-04-10 23:53
Thanks for taking a look at my issue. It's helpful to know that the code is working as it was designed to, but a little disappointing that its not working the way I'd like it to. :)

I see the utility of the timeSelector function in generate being that it allows one to perform calculations at times defined by the function, but I have a hard time imagining cases where it's desirable for a delay to be imposed between the calculation of the result and its being available for use.  I'm sure those exist, but I would think cases where the result needs to be available immediately after calculation would be much more common, and what user's would generally expect, but I guess there are plenty of different perspectives.

In my application the time between iterations could be significant, and holding the result hostage till the next iteration was not acceptable. I've gotten a little better with reactive coding since my original post, and reworked my code in a different way that works for me. Getting the effect I wanted by not really using the resultSelector, and doing that work with a Select in the next step of the pipeline seems obvious now that you point it out, but didn't occur to me at the time. I'll keep that technique in mind for the future.

Thanks again for your time and attention.

**Comment by bartdesmet** [comment] 2019-04-11 00:30
I can see the case where keeping a result object for a long time could be problematic. That's where you'd resort to composing with `Select`.

From this example, you can see why we'd rely on composition wherever possible, rather than having operators that have a lot of fixed behavior (and then possibly end up having `bool` or enum flag confirmation options to influence behavior).

Convenience helpers like `Generate` sometimes tend to do too much, which could otherwise be achieved using composition. In this case, the main purpose of `Generate` is to generate data-dependent delays for each event (unlike composing with `Delay` which provides for a fixed delay). But at the same time, it tries to be consistent with its non-temporal variant whose goal it is to provide a `for (var x = initial; condition(x); x = iterate(x)) { OnNext(result(x)); }` shorthand. These two families of overloads are in conflict with one another when trying to sprinkle in the delay.

Either way, there's a means to get out of this, and I'm glad to hear this discussion helped. I'll close the issue now, but feel free to raise other issues or questions.

**Closed by bartdesmet** 2019-04-11 00:30 UTC
